# Generated by Django 5.2.17 on 2026-10-02 18:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("topic", models.CharField(db_index=True, max_length=100)),
                ("event_key", models.CharField(db_index=True, max_length=255)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("PROCESSED", "Processed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=5)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "events_outbox",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="outbox_status_created_idx"),
                    models.Index(fields=["topic", "event_key"], name="outbox_topic_key_idx"),
                ],
            },
        ),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION protect_events_outbox_mutation()
            RETURNS TRIGGER AS $$
            BEGIN
                IF NEW.id <> OLD.id OR NEW.topic <> OLD.topic
                   OR NEW.event_key <> OLD.event_key
                   OR NEW.payload::text <> OLD.payload::text
                   OR NEW.created_at <> OLD.created_at THEN
                    RAISE EXCEPTION 'events_outbox core fields are immutable';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER events_outbox_mutation_trigger
            BEFORE UPDATE ON events_outbox
            FOR EACH ROW
            EXECUTE FUNCTION protect_events_outbox_mutation();

            CREATE OR REPLACE FUNCTION protect_events_outbox_deletion()
            RETURNS TRIGGER AS $$
            BEGIN
                RAISE EXCEPTION 'events_outbox records are immutable and cannot be deleted';
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER events_outbox_deletion_trigger
            BEFORE DELETE ON events_outbox
            FOR EACH ROW
            EXECUTE FUNCTION protect_events_outbox_deletion();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS events_outbox_deletion_trigger ON events_outbox;
            DROP FUNCTION IF EXISTS protect_events_outbox_deletion();
            DROP TRIGGER IF EXISTS events_outbox_mutation_trigger ON events_outbox;
            DROP FUNCTION IF EXISTS protect_events_outbox_mutation();
            """,
        ),
    ]
