# Generated by Django 5.2.17 on 2026-09-29 15:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login.succeeded", "Login Succeeded"),
                            ("login.failed", "Login Failed"),
                            ("login.blocked", "Login Blocked"),
                            ("logout", "Logout"),
                            ("password.changed", "Password Changed"),
                            ("password.rejected", "Password Rejected"),
                            ("platform_access.granted", "Platform Access Granted"),
                        ],
                        max_length=40,
                    ),
                ),
                ("actor_id", models.UUIDField(null=True)),
                ("subject_id", models.UUIDField(null=True)),
                ("identity_digest", models.CharField(blank=True, max_length=64)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"], name="accounts_se_action_da3cef_idx"
                    )
                ],
            },
        ),
    ]
