# Generated by Django 5.2.17 on 2026-09-30 13:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actor_id", models.UUIDField()),
                ("seller_id", models.UUIDField(db_index=True)),
                ("action", models.CharField(max_length=80)),
                ("target_type", models.CharField(max_length=80)),
                ("target_id", models.UUIDField()),
                ("changes", models.JSONField(default=dict)),
                ("remote_ip", models.GenericIPAddressField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["seller_id", "-created_at"], name="audit_audit_seller__6f6175_idx"
                    )
                ],
            },
        ),
    ]
