# Generated by Django 5.2.17 on 2026-10-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_append_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="seller_id",
            field=models.UUIDField(db_index=True, null=True),
        ),
    ]
