# Generated by Django 5.2.17 on 2026-10-02 04:25

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0002_catalog_integrity"),
        ("inventory", "0002_inventory_integrity"),
        ("sellers", "0005_lifecycle_integrity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("order_number", models.CharField(db_index=True, max_length=64, unique=True)),
                ("customer_email", models.EmailField(max_length=255)),
                ("currency", models.CharField(max_length=3)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "discount_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "shipping_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("authorized", "Authorized"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "fulfillment_status",
                    models.CharField(
                        choices=[
                            ("unfulfilled", "Unfulfilled"),
                            ("partially_fulfilled", "Partially Fulfilled"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="unfulfilled",
                        max_length=32,
                    ),
                ),
                ("billing_address_snapshot", models.JSONField(default=dict)),
                ("shipping_address_snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SellerOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "seller_order_number",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "discount_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "shipping_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "commission_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "seller_net_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seller_orders",
                        to="orders.order",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="sellers.seller",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                ("from_status", models.CharField(max_length=32)),
                ("to_status", models.CharField(max_length=32)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "seller_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_history",
                        to="orders.sellerorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("product_name_snapshot", models.CharField(max_length=255)),
                ("sku_snapshot", models.CharField(max_length=64)),
                ("variant_snapshot", models.JSONField(default=dict)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
                ),
                ("seller_net_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.productvariant",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="inventory.warehouse",
                    ),
                ),
                (
                    "seller_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="orders.sellerorder",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", Decimal("0.00"))),
                name="order_subtotal_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_total__gte", Decimal("0.00"))),
                name="order_discount_total_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_total__gte", Decimal("0.00"))),
                name="order_tax_total_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("shipping_total__gte", Decimal("0.00"))),
                name="order_shipping_total_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("grand_total__gte", Decimal("0.00"))),
                name="order_grand_total_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="sellerorder",
            constraint=models.UniqueConstraint(
                fields=("order", "seller"), name="seller_order_unique_per_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="sellerorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", Decimal("0.00"))),
                name="seller_order_subtotal_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="sellerorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_total__gte", Decimal("0.00"))),
                name="seller_order_discount_total_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="sellerorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_total__gte", Decimal("0.00"))),
                name="seller_order_tax_total_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="sellerorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("shipping_total__gte", Decimal("0.00"))),
                name="seller_order_shipping_total_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="sellerorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("commission_total__gte", Decimal("0.00"))),
                name="seller_order_commission_total_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="sellerorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("seller_net_total__gte", Decimal("0.00"))),
                name="seller_order_seller_net_total_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="order_item_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", Decimal("0.00"))),
                name="order_item_unit_price_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__gte", Decimal("0.00"))),
                name="order_item_discount_amount_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_amount__gte", Decimal("0.00"))),
                name="order_item_tax_amount_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("total__gte", Decimal("0.00"))),
                name="order_item_total_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("commission_amount__gte", Decimal("0.00"))),
                name="order_item_commission_amount_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("seller_net_amount__gte", Decimal("0.00"))),
                name="order_item_seller_net_amount_nonnegative",
            ),
        ),
    ]
