# Generated by Django 5.2.17 on 2026-10-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_orders_integrity"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerorder",
            name="inventory_committed",
            field=models.BooleanField(default=False),
        ),
    ]
