# Generated by Django 5.2.17 on 2026-10-02 09:49

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0002_catalog_integrity"),
        ("sellers", "0007_phase10_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("platform", "Platform"), ("seller", "Seller")],
                        default="seller",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, max_length=1000)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed_amount", "Fixed amount")],
                        max_length=16,
                    ),
                ),
                ("discount_value", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "min_order_amount",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=12),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("stackable", models.BooleanField(default=False)),
                ("priority", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="sellers.seller",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("usage_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("usage_limit_per_customer", models.PositiveIntegerField(blank=True, null=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PromotionCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targeted_promotions",
                        to="catalog.category",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targeted_categories",
                        to="promotions.promotion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromotionProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targeted_promotions",
                        to="catalog.product",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targeted_products",
                        to="promotions.promotion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromotionSeller",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targeted_sellers",
                        to="promotions.promotion",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targeted_promotions",
                        to="sellers.seller",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("order_id", models.UUIDField()),
                ("discount_amount", models.DecimalField(decimal_places=4, max_digits=12)),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usages",
                        to="promotions.coupon",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coupon_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-used_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("discount_amount__gt", Decimal("0"))),
                        name="coupon_usage_discount_positive",
                    ),
                    models.UniqueConstraint(
                        fields=("coupon", "order_id"), name="coupon_order_unique"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scope", "platform"), ("seller__isnull", True)),
                    models.Q(("scope", "seller"), ("seller__isnull", False)),
                    _connector="OR",
                ),
                name="promotion_scope_seller_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_value__gt", Decimal("0"))),
                name="promotion_discount_value_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("discount_type", "percentage"), _negated=True),
                    ("discount_value__lte", Decimal("100.0000")),
                    _connector="OR",
                ),
                name="promotion_percentage_discount_bound",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="promotion_dates_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                condition=models.Q(("code__regex", "^[A-Z0-9_-]{3,32}$")), name="coupon_code_format"
            ),
        ),
        migrations.AddConstraint(
            model_name="promotioncategory",
            constraint=models.UniqueConstraint(
                fields=("promotion", "category"), name="promotion_category_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="promotionproduct",
            constraint=models.UniqueConstraint(
                fields=("promotion", "product"), name="promotion_product_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="promotionseller",
            constraint=models.UniqueConstraint(
                fields=("promotion", "seller"), name="promotion_seller_unique"
            ),
        ),
    ]
