# Generated by Django 5.2.17 on 2026-09-30 04:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("legal_name", models.CharField(max_length=200)),
                ("display_name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("rejected", "Rejected"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("default_currency", models.CharField(default="USD", max_length=3)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_sellers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="SellerPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["code"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("code__regex", "^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)+$")
                        ),
                        name="seller_permission_code_format",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SellerRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("is_system", models.BooleanField(default=True)),
                ("is_owner", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="sellers.seller",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SellerMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                        ],
                        default="invited",
                        max_length=12,
                    ),
                ),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_seller_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="sellers.seller",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seller_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="sellers.sellerrole",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SellerRolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sellers.sellerpermission"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sellers.sellerrole"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sellerrole",
            name="permissions",
            field=models.ManyToManyField(
                through="sellers.SellerRolePermission", to="sellers.sellerpermission"
            ),
        ),
        migrations.AddIndex(
            model_name="seller",
            index=models.Index(
                fields=["status", "created_at"], name="sellers_sel_status_2801c8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="seller",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "active", "suspended", "rejected", "closed"])
                ),
                name="seller_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="seller",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("verification_status__in", ["pending", "verified", "rejected"])
                ),
                name="seller_valid_verification_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="seller",
            constraint=models.CheckConstraint(
                condition=models.Q(("default_currency__regex", "^[A-Z]{3}$")),
                name="seller_currency_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="seller",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("approved_at__isnull", True), ("approved_by__isnull", True)),
                    models.Q(("approved_at__isnull", False), ("approved_by__isnull", False)),
                    _connector="OR",
                ),
                name="seller_approval_metadata_pair",
            ),
        ),
        migrations.AddIndex(
            model_name="sellermembership",
            index=models.Index(
                fields=["user", "status", "seller"], name="sellers_sel_user_id_bfa938_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sellermembership",
            constraint=models.UniqueConstraint(
                fields=("seller", "user"), name="seller_user_membership_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sellermembership",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["invited", "active", "suspended"])),
                name="seller_membership_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="sellermembership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "active"), _negated=True),
                    ("joined_at__isnull", False),
                    _connector="OR",
                ),
                name="seller_active_membership_joined",
            ),
        ),
        migrations.AddConstraint(
            model_name="sellerrolepermission",
            constraint=models.UniqueConstraint(
                fields=("role", "permission"), name="seller_role_permission_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sellerrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_owner", True)),
                fields=("is_owner",),
                name="seller_one_owner_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="sellerrole",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_system", True), ("seller__isnull", True)),
                    models.Q(("is_owner", False), ("is_system", False), ("seller__isnull", False)),
                    _connector="OR",
                ),
                name="seller_role_scope_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="sellerrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("seller__isnull", True)),
                fields=("name",),
                name="seller_global_role_name_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="sellerrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("seller__isnull", False)),
                fields=("seller", "name"),
                name="seller_role_name_unique",
            ),
        ),
    ]
