# Generated by Django 5.2.17 on 2026-09-30 13:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sellers", "0003_tenant_role_integrity"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=2000)),
                ("website", models.URLField(blank=True)),
                (
                    "seller",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profile",
                        to="sellers.seller",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SellerSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                (
                    "seller",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settings",
                        to="sellers.seller",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SellerAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("registered", "Registered"), ("returns", "Returns")],
                        max_length=12,
                    ),
                ),
                ("line1", models.CharField(max_length=200)),
                ("line2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(max_length=2)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="addresses",
                        to="sellers.seller",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("seller", "kind"), name="seller_address_kind_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["registered", "returns"])),
                        name="seller_address_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("country__regex", "^[A-Z]{2}$")),
                        name="seller_address_country_format",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SellerDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("registration", "Business registration"),
                            ("tax", "Tax registration"),
                        ],
                        max_length=16,
                    ),
                ),
                ("storage_key", models.CharField(max_length=200, unique=True)),
                ("content_type", models.CharField(max_length=32)),
                ("size", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("uploaded_by_id", models.UUIDField()),
                ("verified_by_id", models.UUIDField(null=True)),
                ("verified_at", models.DateTimeField(null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=500)),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="sellers.seller",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("document_type__in", ["registration", "tax"])),
                        name="seller_document_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("content_type__in", ["image/png", "image/jpeg"])),
                        name="seller_document_content_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("size__gt", 0), ("size__lte", 5242880)),
                        name="seller_document_size_bounded",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("rejection_reason", ""),
                                ("status", "pending"),
                                ("verified_at__isnull", True),
                                ("verified_by_id__isnull", True),
                            ),
                            models.Q(
                                ("rejection_reason", ""),
                                ("status", "verified"),
                                ("verified_at__isnull", False),
                                ("verified_by_id__isnull", False),
                            ),
                            models.Q(
                                ("status", "rejected"),
                                ("verified_at__isnull", False),
                                ("verified_by_id__isnull", False),
                                models.Q(("rejection_reason", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="seller_document_review_valid",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("seller", "document_type"),
                        name="seller_one_pending_document_type",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SellerStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actor_id", models.UUIDField()),
                ("from_status", models.CharField(blank=True, max_length=16)),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("rejected", "Rejected"),
                            ("closed", "Closed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_history",
                        to="sellers.seller",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "from_status__in",
                                ["", "pending", "active", "suspended", "rejected", "closed"],
                            ),
                            (
                                "to_status__in",
                                ["pending", "active", "suspended", "rejected", "closed"],
                            ),
                        ),
                        name="seller_history_status_valid",
                    )
                ],
            },
        ),
    ]
